# 3.8.5　无法取消的 Promise

一旦创建了一个 Promise 并为其注册了完成和 / 或拒绝处理函数，如果出现某种情况使得这个任务悬而未决的话，你也没有办法从外部停止它的进程。

>很多 Promise 抽象库提供了工具来取消 Promise，但这个思路很可怕！很多开发者希望 Promise 的原生设计就具有外部取消功能，但问题是，这可能会使 Promise 的一个消费者或观察者影响其他消费者查看这个 Promise。这违背了未来值的可信任性（外部不变性），但更坏的是，这是“远隔作用”（action at a distance）反模式的体现。不管看起来如何有用，这实际上会导致你重陷与使用回调同样的噩梦。

考虑前面的 Promise 超时场景：
```
var p = foo(42);

Promise.race([
  p,
  timeoutPromise(3000)
])
.then(
  doSomething,
  handleError
);

p.then(function(){
  // 即使在超时的情况下也会发生 :（
})
```
这个“超时”相对于 promise p 是外部的，所以 p 本身还会继续运行，这一点可能并不是我们所期望的。

一种选择是侵入式地定义你自己的决议回调：
```
var OK = true;

var p = foo(42);

Promise.race([
  p,
  timeoutPromise(3000)
  .catch(function(err){
    OK = false;
    throw err;
  })
])
.then(
  doSomething,
  handleError
);

p.then(function(){
  if(OK){
    // 只在没有超时情况下才会发生 :）
  }
})
```
这很丑陋。它可以工作，但是离理想实现还差很远。一般来说，应避免这样的情况。

但如果没法避免的话，这个解决方案的丑陋应该是一个线索，它提示取消 这个功能属于 Promise 之上更高级的抽象。我建议你应查看 Promise 抽象库以获得帮助，而不是 hack 自己的版本。

>我的 Promise 抽象库 asynquence 提供了这样一个抽象，还有一个为序列提供的abort() 功能，这些内容都会在本部分的附录 A 中讨论。

单独的一个 Promise 并不是一个真正的流程控制机制（至少不是很有意义），这正是取消 所涉及的层次（流程控制）。这就是为什么 Promise 取消总是让人感觉很别扭。

相比之下，集合在一起的 Promise 构成的链，我喜欢称之为一个“序列”，就是一个流程控制的表达，因此将取消定义在这个抽象层次上是合适的。

单独的 Promise 不应该可取消，但是取消一个可序列是合理的，因为你不会像对待 Promise 那样把序列作为一个单独的不变值来传送。